/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.view;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import projeto.dao.FornecedorDAO;
import projeto.dao.FuncionarioDAO;
import projeto.model.Fornecedores;
import projeto.util.Utilitarios;

/**
 *
 * @author edir_
 */
public class FrmFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form CadClient
     */
    
    public void listar(){
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedores> lista = dao.listaFornecedores();
        DefaultTableModel dados = (DefaultTableModel) TbFornecedores.getModel();
        dados.setNumRows(0);
        
        for(Fornecedores c : lista){
         dados.addRow(new Object[]{
         c.getId(),
         c.getNome(),
         c.getCnpj(),
         c.getEmail(),
         c.getTelefone(),
         c.getCelular(),
         c.getCep(),
         c.getEndereco(),
         c.getNumero(),
         c.getComplemento(),
         c.getBairro(),
         c.getCidade(),
         c.getEstado()   
         }); 
        }   
    }
    
    public FrmFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnDadosForn = new javax.swing.JTabbedPane();
        PnCadForn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        TxtNome = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtCnpj = new javax.swing.JFormattedTextField();
        TxtCelular = new javax.swing.JFormattedTextField();
        TxtFixo = new javax.swing.JFormattedTextField();
        TxtCep = new javax.swing.JFormattedTextField();
        TxtEndereco = new javax.swing.JTextField();
        TxtNumero = new javax.swing.JTextField();
        TxtBairro = new javax.swing.JTextField();
        TxtComplemento = new javax.swing.JTextField();
        TxtCidade = new javax.swing.JTextField();
        CbUf = new javax.swing.JComboBox<>();
        BtPesquisar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        PnTabela = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TxtPequisaDaTabela = new javax.swing.JTextField();
        BtPesquisarTabela = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbFornecedores = new javax.swing.JTable();
        BtNovoTabela = new javax.swing.JButton();
        BtConsultarTabela = new javax.swing.JButton();
        BtEditarTabela = new javax.swing.JButton();
        BtDeletarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionários");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Fornecedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Celular:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Código:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("E-mail:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("CNPJ:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("UF:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Bairro:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Complemento:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Cidade:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("CEP:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Endereço:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Número:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Fixo:");

        TxtCodigo.setEditable(false);
        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });

        try {
            TxtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCepActionPerformed(evt);
            }
        });
        TxtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCepKeyPressed(evt);
            }
        });

        CbUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        BtPesquisar.setText("Pesquisar");
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });

        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnCadFornLayout = new javax.swing.GroupLayout(PnCadForn);
        PnCadForn.setLayout(PnCadFornLayout);
        PnCadFornLayout.setHorizontalGroup(
            PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadFornLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnCadFornLayout.createSequentialGroup()
                        .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnCadFornLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnCadFornLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(BtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 1229, Short.MAX_VALUE))
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnCadFornLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnCadFornLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33))
                    .addGroup(PnCadFornLayout.createSequentialGroup()
                        .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(TxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PnCadFornLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnCadFornLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        PnCadFornLayout.setVerticalGroup(
            PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadFornLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(CbUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PnCadFornLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        PnDadosForn.addTab("Dados do Fornecedor", PnCadForn);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Nome:");

        TxtPequisaDaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPequisaDaTabelaActionPerformed(evt);
            }
        });
        TxtPequisaDaTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPequisaDaTabelaKeyPressed(evt);
            }
        });

        BtPesquisarTabela.setText("Pesquisar");
        BtPesquisarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarTabelaActionPerformed(evt);
            }
        });

        TbFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CNPJ", "Email", "Telefone", "Celular", "CEP", "Endereço", "Numero", "Complemento", "Bairro", "Cidade", "Estado"
            }
        ));
        TbFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbFornecedores);

        BtNovoTabela.setText("Novo");
        BtNovoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoTabelaActionPerformed(evt);
            }
        });

        BtConsultarTabela.setText("Consultar");

        BtEditarTabela.setText("Editar");

        BtDeletarTabela.setText("Deletar");

        javax.swing.GroupLayout PnTabelaLayout = new javax.swing.GroupLayout(PnTabela);
        PnTabela.setLayout(PnTabelaLayout);
        PnTabelaLayout.setHorizontalGroup(
            PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnTabelaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPequisaDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtPesquisarTabela))
                    .addGroup(PnTabelaLayout.createSequentialGroup()
                        .addComponent(BtNovoTabela)
                        .addGap(18, 18, 18)
                        .addComponent(BtConsultarTabela)
                        .addGap(18, 18, 18)
                        .addComponent(BtEditarTabela)
                        .addGap(18, 18, 18)
                        .addComponent(BtDeletarTabela)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        PnTabelaLayout.setVerticalGroup(
            PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtPequisaDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisarTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovoTabela)
                    .addComponent(BtConsultarTabela)
                    .addComponent(BtEditarTabela)
                    .addComponent(BtDeletarTabela))
                .addContainerGap())
        );

        PnDadosForn.addTab("Lista de Fornecedores", PnTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnDadosForn, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 49, Short.MAX_VALUE)
                    .addComponent(PnDadosForn, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        
            String nome = TxtNome.getText();
            Fornecedores fun = new Fornecedores();
            FuncionarioDAO dao = new FuncionarioDAO();
            
            
            
        TxtCodigo.setText(String.valueOf(fun.getId()));
        TxtNome.setText(fun.getNome());
        TxtCnpj.setText(fun.getCpf());
        TxtEmail.setText(fun.getEmail());
        TxtFixo.setText(fun.getTelefone());
        TxtCelular.setText(fun.getCelular());
        TxtCep.setText(fun.getCep());
        TxtEndereco.setText(fun.getEndereco());
        TxtNumero.setText(String.valueOf(fun.getNumero()));
        TxtComplemento.setText(fun.getComplemento());
        TxtBairro.setText(fun.getBairro());
        TxtCidade.setText(fun.getCidade());
        CbUf.setSelectedItem(fun.getEstado());
    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    private void BtNovoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoTabelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtNovoTabelaActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed

            Fornecedores forn = new Fornecedores();
            
            forn.setNome(TxtNome.getText());
            forn.setCnpj(TxtCnpj.getText());
            forn.setEmail(TxtEmail.getText());  
            forn.setTelefone(TxtFixo.getText());
            forn.setCelular(TxtCelular.getText());
            forn.setCep(TxtCep.getText());
            forn.setEndereco(TxtEndereco.getText());
            forn.setNumero(Integer.parseInt(TxtNumero.getText()));
            forn.setComplemento(TxtComplemento.getText());
            forn.setBairro(TxtBairro.getText());
            forn.setCidade(TxtCidade.getText());
            forn.setEstado(CbUf.getSelectedItem().toString());
            
            FornecedorDAO dao = new FornecedorDAO();
            dao.cadastrarFornecedor(forn);
            
            new Utilitarios().limpaTela(PnCadForn);
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtPesquisarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarTabelaActionPerformed
         String nome = "%"+TxtPequisaDaTabela.getText()+"%";
        
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedores> lista = (List<Fornecedores>) dao.buscaFornecedorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TbFornecedores.getModel();
        dados.setNumRows(0);
        
        for(Fornecedores c : lista){
         dados.addRow(new Object[]{
         c.getId(),
         c.getNome(),
         c.getCnpj(),
         c.getTelefone(),
         c.getCelular(),
         c.getCep(),
         c.getEndereco(),
         c.getNumero(),
         c.getComplemento(),
         c.getBairro(),
         c.getCidade(),
         c.getEstado()       
         }); 
        }

     new Utilitarios().limpaTela(PnCadForn);        
    }//GEN-LAST:event_BtPesquisarTabelaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TbFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbFornecedoresMouseClicked
        PnDadosForn.setSelectedIndex(0);
        TxtCodigo.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 0).toString());
        TxtNome.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 1).toString());
        TxtCnpj.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 2).toString());
        TxtEmail.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 3).toString());
        TxtFixo.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 4).toString());
        TxtCelular.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 5).toString());
        TxtCep.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 6).toString());
        TxtEndereco.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 7).toString());
        TxtNumero.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 8).toString());
        TxtComplemento.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 9).toString());
        TxtBairro.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 10).toString());
        TxtCidade.setText(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 11).toString());
        CbUf.setSelectedItem(TbFornecedores.getValueAt(TbFornecedores.getSelectedRow(), 12).toString());
        
    }//GEN-LAST:event_TbFornecedoresMouseClicked

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        Fornecedores forn = new Fornecedores();
            
            forn.setNome(TxtNome.getText());
            forn.setCpf(TxtCnpj.getText());
            forn.setEmail(TxtEmail.getText());
            forn.setTelefone(TxtFixo.getText());
            forn.setCelular(TxtCelular.getText());
            forn.setCep(TxtCep.getText());
            forn.setEndereco(TxtEndereco.getText());
            forn.setNumero(Integer.parseInt(TxtNumero.getText()));
            forn.setComplemento(TxtComplemento.getText());
            forn.setBairro(TxtBairro.getText());
            forn.setCidade(TxtCidade.getText());
            forn.setEstado(CbUf.getSelectedItem().toString());
            forn.setId(Integer.parseInt(TxtCodigo.getText()));
            
            FornecedorDAO dao = new FornecedorDAO();
            dao.alteraFornecedor(forn);
            
            new Utilitarios().limpaTela(PnCadForn);
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
       Fornecedores forn = new Fornecedores();
            forn.setId(Integer.parseInt(TxtCodigo.getText()));
            FornecedorDAO dao = new FornecedorDAO();
            dao.deletarFornecedor(forn);
            
            new Utilitarios().limpaTela(PnCadForn);
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void TxtPequisaDaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPequisaDaTabelaActionPerformed

    }//GEN-LAST:event_TxtPequisaDaTabelaActionPerformed

    private void TxtPequisaDaTabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPequisaDaTabelaKeyPressed
//         String nome = "%"+TxtPequisaDaTabela.getText()+"%";
//        
//        FuncionarioDAO dao = new FuncionarioDAO();
//        List<Funcionarios> lista = dao.buscaFuncNome(nome);
//        DefaultTableModel dados = (DefaultTableModel) TbFornecedore.getModel();
//        dados.setNumRows(0);
//        
//        for(Funcionarios c : lista){
//         dados.addRow(new Object[]{
//         c.getId(),
//         c.getNome(),
//         c.getRg(),
//         c.getCpf(),
//         c.getEmail(),
//         c.getSenha(),
//         c.getCargo(),
//         c.getNivelAcesso(),
//         c.getTelefone(),
//         c.getCelular(),
//         c.getCep(),
//         c.getEndereco(),
//         c.getNumero(),
//         c.getComplemento(),
//         c.getBairro(),
//         c.getCidade(),
//         c.getEstado()        
//         }); 
//        }          
    }//GEN-LAST:event_TxtPequisaDaTabelaKeyPressed

    private void TxtCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCepActionPerformed

    private void TxtCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCepKeyPressed
        //Programacao do keypress
	if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Fornecedores obj =  new Fornecedores();
         FornecedorDAO dao = new FornecedorDAO();
         obj = dao.buscaCep(TxtCep.getText());
         
         TxtEndereco.setText(obj.getEndereco());
         TxtBairro.setText(obj.getBairro());
         TxtCidade.setText(obj.getCidade());
         CbUf.setSelectedItem(obj.getEstado());                  
     }
    }//GEN-LAST:event_TxtCepKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultarTabela;
    private javax.swing.JButton BtDeletarTabela;
    private javax.swing.JButton BtEditarTabela;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovoTabela;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtPesquisarTabela;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox<String> CbUf;
    private javax.swing.JPanel PnCadForn;
    private javax.swing.JTabbedPane PnDadosForn;
    private javax.swing.JPanel PnTabela;
    private javax.swing.JTable TbFornecedores;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JFormattedTextField TxtCelular;
    private javax.swing.JFormattedTextField TxtCep;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JFormattedTextField TxtCnpj;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtComplemento;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEndereco;
    private javax.swing.JFormattedTextField TxtFixo;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtPequisaDaTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
