/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.view;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projeto.dao.ClienteDAO;
import projeto.dao.FornecedorDAO;
import projeto.dao.ProdutosDAO;
import projeto.model.Clientes;
import projeto.model.Fornecedores;
import projeto.model.Produtos;
import projeto.util.Utilitarios;

/**
 *
 * @author edir_
 */
public class FrmProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadClient
     */
    
    public void listar(){
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) TbProdutos.getModel();
        dados.setNumRows(0);
        
        for(Produtos c : lista){
         dados.addRow(new Object[]{
         c.getId(),
         c.getDescricao(),
         c.getQtdEstoque(),
         c.getPreco(),
         c.getFornecedor().getNome(),    
         }); 
        }
        
    }
    
    public FrmProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnDadosProd = new javax.swing.JTabbedPane();
        PnCadProd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        TxtDescricao = new javax.swing.JTextField();
        TxtEstoque = new javax.swing.JTextField();
        TxtPreco = new javax.swing.JTextField();
        BtPesquisar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CbFornecedor = new javax.swing.JComboBox();
        PnTabela = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TxtPequisaDaTabela = new javax.swing.JTextField();
        BtPesquisarTabela = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProdutos = new javax.swing.JTable();
        BtNovoTabela = new javax.swing.JButton();
        BtConsultarTabela = new javax.swing.JButton();
        BtEditarTabela = new javax.swing.JButton();
        BtDeletarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Código:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Estoque:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Preço Unitário:");

        TxtCodigo.setEditable(false);
        TxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoActionPerformed(evt);
            }
        });

        BtPesquisar.setText("Pesquisar");
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });

        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Fornecedor:");

        CbFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CbFornecedorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        CbFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbFornecedorMouseClicked(evt);
            }
        });
        CbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnCadProdLayout = new javax.swing.GroupLayout(PnCadProd);
        PnCadProd.setLayout(PnCadProdLayout);
        PnCadProdLayout.setHorizontalGroup(
            PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadProdLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnCadProdLayout.createSequentialGroup()
                        .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PnCadProdLayout.createSequentialGroup()
                        .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnCadProdLayout.createSequentialGroup()
                                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnCadProdLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(BtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnCadProdLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PnCadProdLayout.createSequentialGroup()
                                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(PnCadProdLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(CbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnCadProdLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel15)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33))))
        );
        PnCadProdLayout.setVerticalGroup(
            PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadProdLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisar))
                .addGap(18, 18, 18)
                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(60, 60, 60)
                .addGroup(PnCadProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        PnDadosProd.addTab("Produto", PnCadProd);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Nome:");

        TxtPequisaDaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPequisaDaTabelaActionPerformed(evt);
            }
        });
        TxtPequisaDaTabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPequisaDaTabelaKeyPressed(evt);
            }
        });

        BtPesquisarTabela.setText("Pesquisar");
        BtPesquisarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarTabelaActionPerformed(evt);
            }
        });

        TbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Estoque", "Preço Unitário", "Fornecedor"
            }
        ));
        TbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbProdutos);

        BtNovoTabela.setText("Novo");
        BtNovoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoTabelaActionPerformed(evt);
            }
        });

        BtConsultarTabela.setText("Consultar");

        BtEditarTabela.setText("Editar");

        BtDeletarTabela.setText("Deletar");

        javax.swing.GroupLayout PnTabelaLayout = new javax.swing.GroupLayout(PnTabela);
        PnTabela.setLayout(PnTabelaLayout);
        PnTabelaLayout.setHorizontalGroup(
            PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnTabelaLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPequisaDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtPesquisarTabela))
                    .addGroup(PnTabelaLayout.createSequentialGroup()
                        .addComponent(BtNovoTabela)
                        .addGap(18, 18, 18)
                        .addComponent(BtConsultarTabela)
                        .addGap(18, 18, 18)
                        .addComponent(BtEditarTabela)
                        .addGap(18, 18, 18)
                        .addComponent(BtDeletarTabela)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        PnTabelaLayout.setVerticalGroup(
            PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtPequisaDaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisarTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovoTabela)
                    .addComponent(BtConsultarTabela)
                    .addComponent(BtEditarTabela)
                    .addComponent(BtDeletarTabela))
                .addContainerGap())
        );

        PnDadosProd.addTab("Lista de produtos", PnTabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnDadosProd)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(434, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(PnDadosProd, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtNovoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoTabelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtNovoTabelaActionPerformed

    private void BtPesquisarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarTabelaActionPerformed
         String nome = "%"+TxtPequisaDaTabela.getText()+"%";
        
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.buscaProdutosNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TbProdutos.getModel();
        dados.setNumRows(0);
        
        for(Produtos c : lista){
         dados.addRow(new Object[]{
         c.getId(),
         c.getDescricao(),
         c.getQtdEstoque(),
         c.getPreco(),
         c.getFornecedor().getNome(),     
         }); 
        }

     new Utilitarios().limpaTela(PnCadProd);        
    }//GEN-LAST:event_BtPesquisarTabelaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void TbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbProdutosMouseClicked
        PnDadosProd.setSelectedIndex(0);
        TxtCodigo.setText(TbProdutos.getValueAt(TbProdutos.getSelectedRow(), 0).toString());
        TxtDescricao.setText(TbProdutos.getValueAt(TbProdutos.getSelectedRow(), 1).toString());
        TxtEstoque.setText(TbProdutos.getValueAt(TbProdutos.getSelectedRow(), 2).toString());
        TxtPreco.setText(TbProdutos.getValueAt(TbProdutos.getSelectedRow(), 3).toString()); 
        Fornecedores f = new Fornecedores();
        FornecedorDAO dao = new FornecedorDAO();
        f = dao.consultaFornNome(TbProdutos.getValueAt(TbProdutos.getSelectedRow(), 4).toString());
        CbFornecedor.removeAllItems();
        CbFornecedor.getModel().setSelectedItem(f);
        
    }//GEN-LAST:event_TbProdutosMouseClicked

    private void TxtPequisaDaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPequisaDaTabelaActionPerformed

    }//GEN-LAST:event_TxtPequisaDaTabelaActionPerformed

    private void TxtPequisaDaTabelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPequisaDaTabelaKeyPressed
String nome = "%"+TxtPequisaDaTabela.getText()+"%";
        
        ProdutosDAO dao = new ProdutosDAO();
        List<Produtos> lista = dao.buscaProdutosNome(nome);
        DefaultTableModel dados = (DefaultTableModel) TbProdutos.getModel();
        dados.setNumRows(0);
        
        for(Produtos c : lista){
         dados.addRow(new Object[]{
         c.getId(),
         c.getDescricao(),
         c.getQtdEstoque(),
         c.getPreco(),
         c.getFornecedor().getNome(),      
         }); 
        }          // TODO add your handling code here:
    }//GEN-LAST:event_TxtPequisaDaTabelaKeyPressed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        Produtos prod = new Produtos();
        
        prod.setId(Integer.parseInt(TxtCodigo.getText()));
        prod.setDescricao(TxtDescricao.getText());
        prod.setPreco(Double.parseDouble(TxtPreco.getText()));
        prod.setQtdEstoque(Integer.parseInt(TxtEstoque.getText()));
        
        Fornecedores f = new Fornecedores();
        f = (Fornecedores) CbFornecedor.getSelectedItem();
        prod.setFornecedor(f);
       

        ProdutosDAO dao = new ProdutosDAO();
        dao.alterarProduto(prod);

        new Utilitarios().limpaTela(PnCadProd);
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed

        Produtos prod = new Produtos();

        prod.setDescricao(TxtDescricao.getText());
        prod.setPreco(Double.parseDouble(TxtPreco.getText()));
        prod.setQtdEstoque(Integer.parseInt(TxtEstoque.getText()));
        
        Fornecedores f = new Fornecedores();
        f = (Fornecedores) CbFornecedor.getSelectedItem();
        prod.setFornecedor(f);
       
        ProdutosDAO dao = new ProdutosDAO();
        dao.cadastrarProduto(prod);
        
        new Utilitarios().limpaTela(PnCadProd);
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        Produtos prod = new Produtos();
        prod.setId(Integer.parseInt(TxtCodigo.getText()));
        ProdutosDAO dao = new ProdutosDAO();
        dao.deletarProduto(prod);

        new Utilitarios().limpaTela(PnCadProd);
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed

        String nome = TxtDescricao.getText();
        Produtos prod = new Produtos();
        ProdutosDAO dao = new ProdutosDAO();

        prod=dao.consultaProdutoNome(nome);
        CbFornecedor.removeAllItems();

        if(prod.getDescricao()!=null){
        TxtCodigo.setText(String.valueOf(prod.getId()));
        TxtDescricao.setText(prod.getDescricao());
        TxtPreco.setText(String.valueOf(prod.getPreco()));
        TxtEstoque.setText(String.valueOf(prod.getQtdEstoque()));
        Fornecedores f = new Fornecedores();
        FornecedorDAO fdao = new FornecedorDAO();
        
        f= fdao.consultaFornNome(prod.getFornecedor().getNome());
        CbFornecedor.getModel().setSelectedItem(f);
        }else{
            JOptionPane.showMessageDialog(null, "Produto não encontrado");
        }
        
        
    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void TxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoActionPerformed

    private void CbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbFornecedorActionPerformed

    private void CbFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CbFornecedorAncestorAdded
       FornecedorDAO daoForn = new FornecedorDAO();
       List<Fornecedores> listaForn = daoForn.listaFornecedores();
       CbFornecedor.removeAll();
       
        for (Fornecedores f : listaForn){
            CbFornecedor.addItem(f);
        }
    }//GEN-LAST:event_CbFornecedorAncestorAdded

    private void CbFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbFornecedorMouseClicked
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedores> listaForn = dao.listaFornecedores();
        CbFornecedor.removeAllItems();
        for (Fornecedores f : listaForn){
        CbFornecedor.addItem(f);
    }
    }//GEN-LAST:event_CbFornecedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultarTabela;
    private javax.swing.JButton BtDeletarTabela;
    private javax.swing.JButton BtEditarTabela;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovoTabela;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtPesquisarTabela;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox CbFornecedor;
    private javax.swing.JPanel PnCadProd;
    private javax.swing.JTabbedPane PnDadosProd;
    private javax.swing.JPanel PnTabela;
    private javax.swing.JTable TbProdutos;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtEstoque;
    private javax.swing.JTextField TxtPequisaDaTabela;
    private javax.swing.JTextField TxtPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
